version: 2
java-8-defaults: &java-8-defaults
  working_directory: ~/build-working-directory
  docker:
    - image: circleci/openjdk:8-jdk
      environment:
        JAVA_OPTS: -XX:+UseG1GC
        # Disable Kotlin compiler daemon - https://discuss.kotlinlang.org/t/solved-disable-kotlin-compiler-process-keepalive/2622
        GRADLE_OPTS: -Dkotlin.compiler.execution.strategy="in-process"
java-9-defaults: &java-9-defaults
  working_directory: ~/build-working-directory
  docker:
    - image: circleci/openjdk:9-jdk
      environment:
        # Disable Kotlin compiler daemon - https://discuss.kotlinlang.org/t/solved-disable-kotlin-compiler-process-keepalive/2622
        GRADLE_OPTS: -Dkotlin.compiler.execution.strategy="in-process"

shared-steps:
  generate-cache-key: &generate-cache-key
    run:
      command: |
        mkdir -p build
        find settings.gradle.kts build.gradle.kts gradle buildSrc/src buildSrc/build.gradle.kts -type f -exec sha256sum '{}' \; | tee build/circle-ci-key.txt
      name: Generate cache key
  restore-home-cache: &restore-home-cache
    restore_cache:
      keys:
        - v2-home-cache-{{ checksum "build/circle-ci-key.txt" }}
        - v2-home-cache-
  save-home-cache: &save-home-cache
    save_cache:
      paths:
        - ~/.gradle
      key: v2-home-cache-{{ checksum "build/circle-ci-key.txt" }}
      when: always
  show-java-info: &show-java-info
    run:
      command: |
        java -XshowSettings:vm -XX:+PrintCommandLineFlags -version
        java -XshowSettings:vm -XX:+PrintCommandLineFlags -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -version
        javac -version
      name: Show Java Version
  run-gradle-build: &run-gradle-build
    run:
      command: ./gradlew build --scan --stacktrace
      name: Run Gradle Build
  junit-platform-test-results: &junit-platform-test-results
    store_test_results:
      path: ~/build-working-directory/build/test-results/

jobs:
  test-java-8:
    <<: *java-8-defaults
    steps:
      - checkout
      - *show-java-info
      - *generate-cache-key
      - *restore-home-cache
      - *run-gradle-build
      - *junit-platform-test-results
      - *save-home-cache
  test-java-9:
    <<: *java-9-defaults
    steps:
      - checkout
      - *show-java-info
      - *generate-cache-key
      - *restore-home-cache
      - *run-gradle-build
      - *junit-platform-test-results

workflows:
  version: 2
  build:
    jobs:
      - test-java-8
      - test-java-9
