version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          JAVA_OPTS: -XX:+UseG1GC
          # Disable Kotlin compiler daemon - https://discuss.kotlinlang.org/t/solved-disable-kotlin-compiler-process-keepalive/2622
          GRADLE_OPTS: -Dkotlin.compiler.execution.strategy="in-process"

    working_directory: ~/gradle-test-kit-extensions
    steps:
      - checkout

      - restore_cache:
          keys:
          - home-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/junit5.gradle.kts" }}
          - build-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/junit5.gradle.kts" }}

      - run:
          command: |
            java -XshowSettings:vm -XX:+PrintCommandLineFlags -version
            java -XshowSettings:vm -XX:+PrintCommandLineFlags -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -version
            javac -version
          name: Show Java Version

      - run:
          command: ./gradlew build --stacktrace --scan
          name: Gradle Build

      - save_cache:
          paths:
            - ~/.gradle
          key: home-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/junit5.gradle.kts" }}

      - store_test_results:
          path: ~/gradle-test-kit-extensions/build/test-results/

      - save_cache:
          paths:
            - ~/gradle-test-kit-extensions/.gradle
          key: build-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/junit5.gradle.kts" }}


